routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\EntryController as EntryAdminController;
use App\Http\Controllers\Admin\InvitationController;
use App\Http\Controllers\User\EntryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth']], function () {
    //Route admin
    Route::prefix('admin')->name('admin.')->group(function () {
        Route::resource('invitation', InvitationController::class);
        Route::resource('entry', EntryAdminController::class);
    });
});

Route::resource('entry', EntryController::class);

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/layouts/role/role-navbar.blade.php
 <!-- partial:partials/_navbar.html -->
 <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
     <div class="navbar-brand-wrapper d-flex justify-content-center">
         <div class="navbar-brand-inner-wrapper d-flex justify-content-between align-items-center w-100">
             <a class="navbar-brand brand-logo" href="#">
                 @auth("web")
                 <p>Admin</p>
                 @else
                 <p>Hunt Bazaar</p>
                 @endauth
             </a>
             <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                 <span class="mdi mdi-sort-variant"></span>
             </button>
         </div>
     </div>
     <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
         <!-- search -->

         <ul class="navbar-nav navbar-nav-right">
             @auth("web")
             <li class="nav-item nav-profile dropdown">
                 <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
                     <span class="nav-profile-name">{{ Auth::user()->name }}</span>
                 </a>
                 <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
                     <a class="dropdown-item" href="{{ route('login') }}">
                         <i class="mdi mdi-home menu-icon"></i>
                         Dashboard
                     </a>
                     <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">
                         <i class="mdi mdi-logout text-primary"></i>
                         {{ __('Logout') }}
                     </a>
                     <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                         @csrf
                     </form>
                 </div>
             </li>
             @endauth
         </ul>
         <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button"
             data-toggle="offcanvas">
             <span class="mdi mdi-menu"></span>
         </button>
     </div>
 </nav>

resources/views/layouts/role/role-sidebar.blade.php
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        @auth("web")
        <li class="nav-item">
            <a class="nav-link" href="{{route('admin.invitation.index')}}">
                <i class="mdi mdi-view-headline menu-icon"></i>
                <span class="menu-title">Invitation</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{route('admin.entry.index')}}">
                <i class="mdi mdi-view-headline menu-icon"></i>
                <span class="menu-title">Entry</span>
            </a>
        </li>
        @endauth
    </ul>
</nav>