routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\EntryController as EntryAdminController;
use App\Http\Controllers\Admin\InvitationController;
use App\Http\Controllers\User\EntryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth']], function () {
    //Route admin
    Route::prefix('admin')->name('admin.')->group(function () {
        Route::resource('invitation', InvitationController::class);
        Route::resource('entry', EntryAdminController::class);
    });
});

Route::resource('entry', EntryController::class);

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Invitation.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Invitation extends Model
{
    use HasFactory;

    public function status()
    {
        return $this->belongsTo(Status::class);
    }

    public function entry()
    {
        return $this->hasOne(Entry::class);
    }
}

app/Http/Controllers/Admin/InvitationController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Invitation;
use App\Models\Status;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class InvitationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $keyword = $request->input('keyword');

        $invitations = Invitation::with('status')->where(function ($query) use ($keyword) {
            if (isset($keyword)) {
                $query->where('email', 'LIKE', '%' . $keyword . '%');
            }
        })->latest()->paginate(10);

        return view('admin.invitations.index', compact('invitations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.invitations.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function send($generatedLink, $realLink, $email)
    {
        $details = [
            'title' => 'Event Hunt Bazaar December 12th 2021',
            'body' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit deserunt laborum dolores at officia blanditiis commodi cupiditate nobis, totam quibusdam ullam numquam hic dolorem fugiat exercitationem consectetur, quia praesentium quas!',
            'link' => $generatedLink,
            'realLink' => $realLink,
        ];

        try {
            \Mail::to($email)->send(new \App\Mail\InvitationMail($details));
            echo "Success.";
        } catch (\Exception $e) {
            echo "Failed $e.";
        }
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'email' => 'required|email',
        ], [
            'email.required' => 'Please input email',
            'email.emmail' => 'Please input correct format',
        ]);

        $randomString = Str::random(5);
        $link = 'huntbazaar.com/';
        $status = Status::where('slug', 'send')->first();

        try {
            $invitation = new Invitation();
            $invitation->status_id = $status->id;
            $invitation->email = $request->email;
            $invitation->invitation_token = $randomString;
            $invitation->invitation_link = $link . $randomString;
            $invitation->save();

            $invitationLink = Invitation::find($invitation->id);
            $invitationLink->real_link = route('entry.show', $invitation->id);
            $invitationLink->save();

            $this->send($invitation->invitation_link, $invitationLink->real_link, $invitation->email);
        } catch (\Throwable $th) {
            $error = [
                'class' => 'alert-danger',
                'message' => "Failed to send email",
            ];

            return back()->with($error);
        }

        $status = [
            'class' => 'alert-success',
            'message' => "Success Send Email",
        ];

        return redirect()->route('admin.invitation.index')->with($status);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/invitations/create.blade.php
@extends('layouts.master')

@section('css')

@endsection

@section('content')
<div class="container-scroller">
    @include('layouts.role.role-navbar')

    <!-- partial -->
    <div class="container-fluid page-body-wrapper">
        @include('layouts.role.role-sidebar')
        <div class="main-panel" style="overflow-y: scroll; height:450px;">

            <div class="content-wrapper">

                <div class="row">
                    <div class="col-md-12 stretch-card">
                        <div class="card">
                            <div class="card-body" style="min-height: 600px;">
                                <h4 class="card-title">Add Invitation</h4>
                                @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                                @endif
                                @if (session('message'))
                                <div class="alert {{ session('class') }}">
                                    {{ session('message') }}
                                </div>
                                @endif
                                <p class="card-description">
                                    Form send invitation via email
                                </p>
                                <form class="forms-sample" method="POST" action="{{ route('admin.invitation.store') }}"
                                    enctype="multipart/form-data">
                                    @csrf
                                    {!!Form::text('email', 'Email')
                                    ->placeholder('Input Email')->type('email')->required() !!}
                                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                                    <button class="btn btn-light">Cancel</button>
                                </form>
                            </div>
                        </div>
                    </div>

                </div> <!-- row -->

            </div> <!-- content-wrapper ends -->

            @endsection

            @section('js')
            @endsection

resources/views/admin/invitations/index.blade.php
@extends('layouts.master')

@section('css')

@endsection

@section('content')
<div class="container-scroller">
    @include('layouts.role.role-navbar')

    <!-- partial -->
    <div class="container-fluid page-body-wrapper">
        @include('layouts.role.role-sidebar')
        <div class="main-panel" style="overflow-y: scroll; height:450px;">

            <div class="content-wrapper">

                <div class="row">
                    <div class="col-md-12 stretch-card">
                        <div class="card">
                            <div class="card-body" style="min-height: 600px;">
                                <p class="card-title">Data Invitations</p>
                                <p class="card-description">
                                    @if (session('message'))
                                <div class="alert {{ session('class') }}">
                                    {{ session('message') }}
                                </div>
                                @endif
                                </p>
                                <div class="row justify-content-between mb-3">
                                    <div class="col-md-4">
                                        <a href="{{ route('admin.invitation.create') }}" type="button"
                                            class="btn btn-success btn-sm">Input data Invitation</a>
                                    </div>
                                    <div class="col-md-4">
                                        <form method="GET" class="form-inline"
                                            action="{{ route('admin.invitation.index') }}">
                                            <input type="text" class="form-control form-control-sm" name="keyword"
                                                placeholder="Search email .." value="{{ old('keyword') }}">
                                            <button type="submit" class="btn btn-primary btn-sm">Cari</button>
                                        </form>
                                    </div>

                                </div>


                                <div class="table-responsive">
                                    <table id="alumnii" class="table table-bordered table-striped">
                                        <thead>
                                            <tr>
                                                <th>Email</th>
                                                <th>Status</th>

                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($invitations as $invitation)
                                            <tr>
                                                <td>{{ $invitation->email }}</td>
                                                <td>{{ $invitation->status->name }}</td>
                                            </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                    {{ $invitations->appends(['keyword' => old('keyword') ])->links() }}
                                </div>
                            </div>

                        </div>
                    </div> <!-- row -->

                </div> <!-- content-wrapper ends -->
                @endsection

                @section('js')

                @endsection