routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\EntryController as EntryAdminController;
use App\Http\Controllers\Admin\InvitationController;
use App\Http\Controllers\User\EntryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth']], function () {
    //Route admin
    Route::prefix('admin')->name('admin.')->group(function () {
        Route::resource('invitation', InvitationController::class);
        Route::resource('entry', EntryAdminController::class);
    });
});

Route::resource('entry', EntryController::class);

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Entry.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Entry extends Model
{
    use HasFactory;

    protected $casts = [
        'favorite_designer' => 'array'
    ];

    public function invitation()
    {
        return $this->belongsTo(Invitation::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/EntryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Entry;
use Illuminate\Http\Request;

class EntryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $keyword = $request->input('keyword');

        $entries = Entry::with('invitation')->where(function ($query) use ($keyword) {
            if (isset($keyword)) {
                $query->where('email', 'LIKE', '%' . $keyword . '%');
            }
        })->latest()->paginate(10);

        return view('admin.entries.index', compact('entries'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/User/EntryController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Designer;
use App\Models\Entry;
use App\Models\Invitation;
use App\Models\Status;
use Illuminate\Http\Request;

class EntryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function send($token, $email)
    {
        $details = [
            'title' => 'Thank You for Being Involved in Event Hunt Bazaar December 12th 2021',
            'body' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit deserunt laborum dolores at officia blanditiis commodi cupiditate nobis, totam quibusdam ullam numquam hic dolorem fugiat exercitationem consectetur, quia praesentium quas!',
            'token' => $token,
        ];

        try {
            \Mail::to($email)->delay(360)->send(new \App\Mail\ThanksMail($details));
            echo "Success.";
        } catch (\Exception $e) {
            echo "Failed $e.";
        }
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'email' => 'required|email',
            'birth_date' => 'required',
            'gender' => 'required',
            'designer' => 'required',
        ], [
            'email.required' => 'Please input email',
            'email.email' => 'Please input correct format',
            'birth_date.required' => 'Please input birth date',
            'gender.required' => 'Please input gender',
            'designer.required' => 'Please input designer',
        ]);

        $status = Status::where('slug', 'registered')->first();

        try {
            $entry = new Entry();
            $entry->invitation_id = $request->invitation_id;
            $entry->email = $request->email;
            $entry->date_of_birth = $request->birth_date;
            $entry->gender = $request->gender;
            $entry->favorite_designer = $request->designer;
            $entry->save();

            $invitation = Invitation::find($request->invitation_id);
            $invitation->status_id = $status->id;
            $invitation->save();

            $this->send($invitation->invitation_token, $invitation->email);
        } catch (\Throwable $th) {
            $error = [
                'class' => 'alert-danger',
                'message' => "Failed to register",
            ];

            return back()->with($error);
        }

        $status = [
            'class' => 'alert-success',
            'message' => "Success register",
        ];

        return back()->with($status);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $id)
    {
        $invitation = Invitation::find($id);
        $checkInvitation = Entry::where('invitation_id', $invitation->id)->exists();
        $designers = Designer::get();

        return view('user.entries.show', compact('invitation', 'checkInvitation', 'designers'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function loadDataDesigner(Request $request)
    {
        $data = [];

        if ($request->has('q')) {
            $search = $request->q;
            $data = Designer::select('id', 'name')
                ->where('name', 'LIKE', '%' . $search . '%')
                ->get();
        }

        return response()->json($data);
    }
}

resources/views/user/entries/show.blade.php
@extends('layouts.master')

@section('css')
<link rel="stylesheet" href="{{ asset('assets/vendor/select2/css/select2.min.css') }}">
@endsection

@section('content')
<div class="container-scroller">
    @include('layouts.role.role-navbar')

    <!-- partial -->
    <div class="container-fluid page-body-wrapper">
        @include('layouts.role.role-sidebar')
        <div class="main-panel" style="overflow-y: scroll; height:450px;">

            <div class="content-wrapper">
                @if($checkInvitation == 0)
                <div class="row">
                    <div class="col-md-12 stretch-card">
                        <div class="card">
                            <div class="card-body" style="min-height: 600px;">
                                <template>
                                    @{{ timerCount }}
                                </template>
                                <h4 class="card-title">This invitation is for {{$invitation->email}}</h4>
                                @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                                @endif
                                @if (session('message'))
                                <div class="alert {{ session('class') }}">
                                    {{ session('message') }}
                                </div>
                                @endif
                                <p class="card-description">
                                    Please fill out the form below
                                </p>
                                <form method="POST" action="{{ route('entry.store') }}">
                                    @csrf
                                    <input type="hidden" name="invitation_id" value="{{$invitation->id}}">
                                    <div class="row">
                                        <div class="col-md-12">
                                            {!!Form::text('email', 'Email')->value($invitation->email)
                                            ->placeholder('InputEmail')->type('email')->readonly()->required() !!}
                                        </div>

                                        <div class="col-md-12">
                                            {!!Form::text('birth_date', 'Birth Date')
                                            ->placeholder('Input Date')->type('date') !!}
                                        </div>

                                        <div class="col-md-12">
                                            {!!Form::select('gender', 'Choose your gender', [1 => 'Male', 2 => 'Female',
                                            3 => 'Others'])->placeholder('Choose your gender')->required() !!}
                                        </div>

                                        <div class="col-md-12">
                                            <div class="form-group"><label for="">Favorite Designer</label>
                                                <select name="designer[]" class="form-control select2" required
                                                    data-placeholder="Search Designer" multiple="multiple">
                                                    @foreach($designers as $designer)
                                                    <option value="{{$designer->name}}">{{$designer->name}}</option>
                                                    @endforeach
                                                </select>
                                                @error('designer[]')
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                                @enderror
                                            </div>
                                        </div>

                                        <div class="col-md-12 mt-5">
                                            <div class="col-md-6 offset-md-4">
                                                <button type="submit" class="btn btn-primary">
                                                    {{ __('Register') }}
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>

                </div> <!-- row -->
                @else
                <div class="row">
                    <div class="col-md-12 stretch-card">
                        <div class="card">
                            <div class="card-body" style="min-height: 600px;">
                                <h4 class="card-title">Congratulations!</h4>
                                <p class="card-description">
                                    You have been registered in this event. Here is your invitation code :
                                    {{$invitation->invitation_token}}
                                </p>
                            </div>
                        </div>
                    </div>

                </div>
                @endif
            </div> <!-- content-wrapper ends -->
            @endsection

            @section('js')
            <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
            <script src="{{ asset('assets/vendor/select2/js/select2.full.min.js') }}"></script>
            <script>
            function getDesignerSelection() {
                $('.select2').select2({
                    width: 'resolve',
                    ajax: {
                        url: "/api/get-designer",
                        dataType: 'json',
                        delay: 250,
                        processResults: function(data) {
                            return {
                                results: $.map(data, function(item) {
                                    return {
                                        text: item.name,
                                        id: item.id
                                    }

                                })
                            };
                        },
                        cache: true
                    },
                    minimumInputLength: 1,
                    language: {
                        inputTooShort: function() {
                            return 'Silahkan masukkan minimal 1 karakter untuk mencari data';
                        }
                    }
                });

                $('.select2').select2();
            }

            $(function() {
                getDesignerSelection();
            });
            </script>
            @endsection